-- Schema for CMS application (matches code usage in PHP files)
-- Run this in MySQL (e.g. via phpMyAdmin or mysql CLI)

-- Disable foreign key checks while dropping
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `comments`;
DROP TABLE IF EXISTS `posts`;
DROP TABLE IF EXISTS `categories`;
DROP TABLE IF EXISTS `users`;

SET FOREIGN_KEY_CHECKS = 1;

-- Users table
CREATE TABLE `users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_firstname` VARCHAR(100) DEFAULT NULL,
  `user_lastname` VARCHAR(100) DEFAULT NULL,
  `user_email` VARCHAR(255) DEFAULT NULL,
  `user_image` VARCHAR(255) DEFAULT NULL,
  `user_role` VARCHAR(50) DEFAULT 'subscriber',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `username_unique` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Categories table
CREATE TABLE `categories` (
  `cat_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cat_title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cat_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Posts table
CREATE TABLE `posts` (
  `post_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_category_id` INT UNSIGNED DEFAULT NULL,
  `post_title` VARCHAR(255) NOT NULL,
  `post_author` VARCHAR(255) DEFAULT NULL,
  `post_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `post_image` VARCHAR(255) DEFAULT NULL,
  `post_content` TEXT,
  `post_tags` VARCHAR(255) DEFAULT NULL,
  `post_comment_count` INT DEFAULT 0,
  `post_status` VARCHAR(50) DEFAULT 'draft',
  PRIMARY KEY (`post_id`),
  KEY `idx_post_category` (`post_category_id`),
  CONSTRAINT `fk_posts_category` FOREIGN KEY (`post_category_id`) REFERENCES `categories`(`cat_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Comments table
CREATE TABLE `comments` (
  `comment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment_post_id` INT UNSIGNED NOT NULL,
  `comment_author` VARCHAR(255) DEFAULT NULL,
  `comment_email` VARCHAR(255) DEFAULT NULL,
  `comment_content` TEXT,
  `comment_status` VARCHAR(50) DEFAULT 'Unapproved',
  `comment_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`comment_id`),
  KEY `idx_comment_post` (`comment_post_id`),
  CONSTRAINT `fk_comments_post` FOREIGN KEY (`comment_post_id`) REFERENCES `posts`(`post_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Sample admin user (example using MD5 for convenience).
-- IMPORTANT: The application may expect hashed passwords. Prefer inserting a bcrypt hash generated by PHP's password_hash().
-- Example to generate a bcrypt hash in PHP: <?php echo password_hash('your-password-here', PASSWORD_BCRYPT); ?>

INSERT INTO `users` (`username`, `user_password`, `user_firstname`, `user_lastname`, `user_email`, `user_image`, `user_role`)
VALUES ('admin', MD5('admin123'), 'Admin', 'User', 'admin@example.com', NULL, 'admin');

-- Notes:
-- 1) Column names are matched to the code: `posts` (post_id, post_category_id, post_title, post_author, post_date, post_image, post_content, post_tags, post_comment_count, post_status)
--    `categories` (cat_id, cat_title)
--    `comments` (comment_id, comment_post_id, comment_author, comment_email, comment_content, comment_status, comment_date)
--    `users` (user_id, username, user_password, user_firstname, user_lastname, user_email, user_image, user_role)
-- 2) Adjust password storage to match your authentication implementation. If the app uses plain-text passwords (not recommended) you can replace MD5(...) with the plain string.
-- 3) If you prefer no foreign keys (e.g., MyISAM), remove CONSTRAINT lines and/or change the engine.
-- 4) After running this script, import some categories and posts, and confirm paths to the `images/` folder exist (the code references images/<filename>).
